using CSV
using Random
using Dates

names = [
    "OLIVER",
    "HENRY",
    "NOAH",
    "LEO",
    "WILLIAM",
    "CHARLIE",
    "JACK",
    "LUCAS",
    "JAMES",
    "ELIJAH",
    "ARCHIE",
    "ARCHER",
    "LIAM",
    "HARRISON",
    "HUNTER",
    "LEVI",
    "OSCAR",
    "THOMAS",
    "HUDSON",
    "HARVEY",
    "HARRY",
    "HUGO",
    "SEBASTIAN",
    "LUCA",
    "MAX",
    "THEODORE",
    "ETHAN",
    "LACHLAN",
    "ARTHUR",
    "ALEXANDER",
    "GEORGE",
    "ARLO",
    "ISAAC",
    "JACKSON",
    "LINCOLN",
    "AUSTIN",
    "LOGAN",
    "EDWARD",
    "JACOB",
    "RILEY",
    "SAMUEL",
    "COOPER",
    "LOUIS",
    "MASON",
    "RORY",
    "SPENCER",
    "ALFIE",
    "DARCY",
    "FINN",
    "PATRICK",
    "BENJAMIN",
    "ANGUS",
    "FLYNN",
    "JUDE",
    "RYAN",
    "CONNOR",
    "PARKER",
    "JORDAN",
    "OWEN",
    "XAVIER",
    "JASPER",
    "JOSHUA",
    "ASHER",
    "ELI",
    "FELIX",
    "BODHI",
    "HAMISH",
    "CARTER",
    "DANIEL",
    "ELLIOT",
    "SONNY",
    "ZACHARY",
    "JOSEPH",
    "JAXON",
    "KAI",
    "NATE",
    "RIVER",
    "CALEB",
    "FINLEY",
    "WYATT",
    "ARI",
    "BLAKE",
    "LUKA",
    "MICHAEL",
    "AIDEN",
    "BEAU",
    "CHARLES",
    "JAYDEN",
    "RYDER",
    "BRODIE",
    "FLETCHER",
    "ALFRED",
    "MARCUS",
    "GABRIEL",
    "LEWIS",
    "ALBY",
    "AXEL",
    "BILLY",
    "CHASE",
    "LENNY",
    "CHARLOTTE",
    "OLIVIA",
    "AMELIA",
    "AVA",
    "ISLA",
    "GRACE",
    "ELLA",
    "HARPER",
    "WILLOW",
    "IVY",
    "MIA",
    "SOPHIE",
    "MATILDA",
    "EVELYN",
    "CHLOE",
    "DAISY",
    "EVIE",
    "LUCY",
    "ELSIE",
    "LILY",
    "RUBY",
    "SOPHIA",
    "ZOE",
    "HAZEL",
    "FLORENCE",
    "SIENNA",
    "ABIGAIL",
    "ISABELLA",
    "LAYLA",
    "ALICE",
    "ELLIE",
    "MILA",
    "EMILY",
    "ZARA",
    "SADIE",
    "HARRIET",
    "PENELOPE",
    "GEORGIA",
    "ARIA",
    "MACKENZIE",
    "ADDISON",
    "VIOLET",
    "ELEANOR",
    "EMILIA",
    "IMOGEN",
    "FRANKIE",
    "HANNAH",
    "MAYA",
    "SCARLETT",
    "AYLA",
    "SOFIA",
    "ISABELLE",
    "ROSIE",
    "SUMMER",
    "AMBER",
    "LUNA",
    "POPPY",
    "SAVANNAH",
    "EVA",
    "JASMINE",
    "PAIGE",
    "STELLA",
    "ARIANA",
    "AURORA",
    "EMMA",
    "LARA",
    "LOLA",
    "MAGGIE",
    "AUDREY",
    "LILLY",
    "OLIVE",
    "AALIYAH",
    "ANNABELLE",
    "AUBREY",
    "BILLIE",
    "ADELINE",
    "BONNIE",
    "MADISON",
    "ROSE",
    "CHARLIE",
    "ESTHER",
    "FREYA",
    "MADDISON",
    "MAEVE",
    "MAISIE",
    "PIPPA",
    "ADA",
    "ALYSSA",
    "ANASTASIA",
    "CLAIRE",
    "ELIZA",
    "MARGOT",
    "PHOEBE",
    "HARLOW",
    "PIPER",
    "REMI",
    "AMALIA",
    "CLARA",
    "EDEN",
    "HALLIE",
]

start_date = Date("2020-04-12")
end_date = Date("2020-04-16")
orders_per_day = 100
frac = 1 - 1/orders_per_day

orders = []

for date in start_date:Day(1):end_date
    while rand() < frac
        time = Time("9:00:00") + Second(round(8*60*60*rand()))
        push!(orders, (;
            datetime = date + time,
            name = rand(names),
            amount = round(100 + 1000 * rand()) / 1000
        ))
    end
end

CSV.write("orders.csv", orders)